services:
  rabbitmq1:
    image: rabbitmq:4-management
    hostname: rabbitmq1
    volumes:
      - ./storage/mnesia1:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
    ports:
      - 5672:5672
#      - 7672:5672
      - 17672:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=123123
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=rabbitmq1
#
#  rabbitmq2:
#    image: rabbitmq:4-management
#    links:
#      - rabbitmq1
#    hostname: rabbitmq2
#    volumes:
#      - ./storage/mnesia2:/var/lib/rabbitmq
#      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
##    ports:
##      - 6672:5672
##      - 16672:15672
#    environment:
#      - JOIN_CLUSTER_HOST=rabbitmq1
##      - RABBITMQ_NODE_TYPE=disc
##      - RABBITMQ_ERLANG_COOKIE=123123
##      - RABBITMQ_DEFAULT_USER=admin
##      - RABBITMQ_DEFAULT_PASS=admin
##      - RABBITMQ_DEFAULT_VHOST=rabbitmq1
#
#  rabbitmq3:
#    image: rabbitmq:4-management
#    links:
#      - rabbitmq1
#    hostname: rabbitmq3
#    volumes:
#      - ./storage/mnesia3:/var/lib/rabbitmq
#      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf
##    ports:
##      - 8672:5672
##      - 18672:15672
#    environment:
#      - JOIN_CLUSTER_HOST=rabbitmq1
##      - RABBITMQ_ERLANG_COOKIE=123123
##      - RABBITMQ_DEFAULT_USER=admin
##      - RABBITMQ_DEFAULT_PASS=admin
##      - RABBITMQ_DEFAULT_VHOST=rabbitmq1

#  haproxy:
#    image: haproxy:3.0.5
#    ports:
#      - 5672:5672
#      - 15672:15672
#    environment:
#      - HAPROXY_BIND_IP=0.0.0.0
#      - HAPROXY_PORT=5672
#      - HAPROXY_RABBITMQ_CLUSTER=true
#    volumes:
#      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#    depends_on:
#      - rabbitmq1
#      - rabbitmq2
#      - rabbitmq3
